name: GCP Deploy
on:
  push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint
        id : lint-step
        #continue-on-error: true
        run: npm run lint
      - name: check-lint
        if: failure() && steps.lint-step.outcome == 'failure'
        run: echo "Codigo precisa ser revisto!!"
  build-and-deploy:
    needs: lint
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest
    
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      
      - name: 'Configure Docker for Artifact Registry'
        run: gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      
      - name: 'Build and Push Docker image'
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          
          tags: us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webacademy-repo/webacademy:latest

      
      - name: 'Deploy Docker image to Cloud Run'
        run: >
          gcloud run deploy wacicd 
          --image ${{ steps.build-push.outputs.digest }}
          --region us-west1 
          --memory 128Mi 
          --min-instances 0 
          --max-instances 1 
          --platform managed 
          --port 8080 
          --allow-unauthenticated